<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="<?php echo BASE_URL ?>js/_borrarRegistro.js"></script>
<script src="<?php echo BASE_URL ?>js/_actualizarRegistro.js"></script>
<script src="<?php echo BASE_URL ?>js/_actualizarRegistroForm.js"></script>
<script src="<?php echo BASE_URL ?>js/_mensajeEnviado.js"></script>
<script src="<?php echo BASE_URL ?>js/_scrollBehavior.js"></script>